title: Abhinav Chanana - Resume
description: Professional resume of Abhinav Chanana
author: Abhinav Chanana
email: abhinav.chanana@gmail.com

# Theme
remote_theme: pages-themes/minimal@v0.2.0

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/

# Include files
include:
  - _pages

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# GitHub Pages
repository: abhinavchanana/abhichan.github.io
